### PR TITLE
Highway doc fix

### PR DESCRIPTION
**Pull request by mattya**
Sorry for late response.  I fixed some style of mathematical formula on the doc.
Please check it.

### CODE REVIEW

**Comment by fukatani** [comment]
Thanks for your great help!

By the way, if you know, could you tell me good method to check rst file?
I tried Sphinx and http://rst.ninjs.org/ .
But some description such as //sigma doesn't work.

**Comment by fukatani** [comment]
I think blank line at last is needed, but I'd add it.

**Comment by mattya** [comment]
We normally use Sphinx to make the document, so please try following procedure.
1. Reinstall sphinx
2. Reinstall chainer (`python setup.py install`).  You must take this step every time you make a change to the document.
3. `make html` in the `docs` directory
4. document pages are generated in the `docs/build/html`

**Comment by fukatani** [comment]
Thanks! I succeeded to build html and checked it.

**Pull request merged**
